Repository schlanger/QcmReactNative, pull requests merged in 2024-06, with the labels that each got.

#1 Update le SDK avec la nouvelle version
  package-lock.json
  package.json
  src/app/test.tsx
Labels: question

#4 Création composants
  src/Component/MyButton.tsx
  src/app/index.tsx
  src/app/test.tsx
Labels: review

#7 Couleur Navbar
  src/app/_layout.tsx
  src/app/index.tsx
  src/app/test.tsx
Labels: Style

#9 Style et ajout du logo
  assets/MonImage.jpeg
  src/Component/MyButton.tsx
  src/app/index.tsx
Labels: Style

#12 ajout du score fonctionnel
  .idea/sonarlint/issuestore/c/4/c459af1d6710873fe9df2c8f4bc9140d11d658a1
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/c/4/c459af1d6710873fe9df2c8f4bc9140d11d658a1
  .idea/sonarlint/securityhotspotstore/index.pb
  src/app/test.tsx
Labels: review

#14 Create README.md
  README.md
Labels: documentation, review

#16 Update READ.me
  .idea/sonarlint/issuestore/8/e/8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/8/e/8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d
  .idea/sonarlint/securityhotspotstore/index.pb
  README.md
Labels: review

#17 Update README.md
  README.md
Labels: documentation, review

#19 Ajout de la page résultat
  assets/trophé.png
  src/app/index.tsx
  src/app/qcm.tsx
  src/app/result.tsx
Labels: review, score
